# only used for manual setup, but removed versions juuust in case
name: gym-mupen64plus
channels:
- anaconda-fusion
- defaults
dependencies:
- openssl
- pip
- python
- readline
- setuptools
- sqlite
- tk
- wheel
- zlib
- pip:
  - gym
  - numpy
  - PyYAML
  - termcolor
  - mss

